[versions]
agp = "8.4.0-beta01"
androidx-roomRuntime = "2.6.1"
bugsnagAndroid = "6.2.0"
flexbox = "3.0.0"
gsonVersion = "2.10.1"
kotlinxCoroutinesAndroid = "1.8.0"

okhttp = "4.12.0"
remotepreferences = "0.8"
rhino = "1.7.14"
robolectric = "4.11.1"
roomCompiler = "2.6.1"
round = "1.1.2"
toaster = "12.6"
xposed = "82"
gson = "2.10.1"
htmlKtx = "1.1.2"
kotlin = "1.9.21"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
themeEngine = "-SNAPSHOT"
ultimateBarX = "dev-SNAPSHOT"
navigationFragment = "2.7.7"
browser = "1.8.0"
activity = "1.8.2"
constraintlayout = "2.1.4"

[libraries]
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragment" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragment" }
androidx-room-compiler-v251 = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-roomRuntime" }
androidx-room-runtime-v251 = { module = "androidx.room:room-runtime", version.ref = "androidx-roomRuntime" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnagAndroid" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
gson-v288 = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
remotepreferences = { module = "com.crossbowffs.remotepreferences:remotepreferences", version.ref = "remotepreferences" }
rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
round = { module = "io.github.xiaofeidev:round", version.ref = "round" }
toaster = { module = "com.github.getActivity:Toaster", version.ref = "toaster" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
html-ktx = { module = "dev.rikka.rikkax.html:html-ktx", version.ref = "htmlKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version = "1.12.0-alpha03" }

themeEngine = { module = "com.github.AnkioTomas:ThemeEngine", version.ref = "themeEngine" }

ultimateBarX = { module = "com.github.zackratos:UltimateBarX", version.ref = "ultimateBarX" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

