[versions]
agp = "8.3.0-alpha07"
analytics = "14.3.0"
androiddebuglib = "0.1.4"
androidx-roomRuntime = "2.5.2"
easyFloat = "2.0.4"
flexbox = "3.0.0"
github-DialogLoading = "1.0.3"

kotlinReflect = "1.8.22"
kotlinxCoroutinesAndroid = "1.6.4"
kotlinxHtml = "0.1.0"
markdown = "0.5.0"
remotepreferences = "0.8"
rhino = "1.7.14"
roomCompiler = "2.5.2"
round = "1.1.2"
sqliteFramework = "2.3.1"
swiperefreshlayout = "1.2.0-alpha01"
vovMarkdown = "2.0.1"
xposed = "82"
gson = "2.10.1"
htmlKtx = "1.1.2"
kotlin = "1.8.21"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.9.0"
okhttp = "4.11.0"
permissionx = "1.7.1"
themeEngine = "1.1.0"
ultimateBarX = "dev-SNAPSHOT"
navigationFragment = "2.7.0"
browser = "1.6.0"

[libraries]
analytics = { module = "com.flurry.android:analytics", version.ref = "analytics" }
androiddebuglib = { module = "com.itlgl.android:androiddebuglib", version.ref = "androiddebuglib" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragment" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragment" }
androidx-room-compiler-v251 = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-roomRuntime" }
androidx-room-runtime-v251 = { module = "androidx.room:room-runtime", version.ref = "androidx-roomRuntime" }
androidx-sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqliteFramework" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
easyFloat = { module = "com.github.princekin-f:EasyFloat", version.ref = "easyFloat" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinxHtml" }
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
remotepreferences = { module = "com.crossbowffs.remotepreferences:remotepreferences", version.ref = "remotepreferences" }
rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }
round = { module = "io.github.xiaofeidev:round", version.ref = "round" }
tobeyr1DialogLoading = { module = "com.github.Tobeyr1:DialogLoading", version.ref = "github-DialogLoading" }
vov-markdown = { module = "org.vov.markdown:vov-markdown", version.ref = "vovMarkdown" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
html-ktx = { module = "dev.rikka.rikkax.html:html-ktx", version.ref = "htmlKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
permissionx = { module = "com.guolindev.permissionx:permissionx", version.ref = "permissionx" }
themeEngine = { module = "io.github.prathameshmm02.themeEngine:themeEngine", version.ref = "themeEngine" }
ultimateBarX = { module = "com.github.zackratos:UltimateBarX", version.ref = "ultimateBarX" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

