[versions]
agp = "8.4.0-alpha04"
androidx-roomRuntime = "2.5.2"
bugsnagAndroid = "5.32.1"
flexbox = "3.0.0"
github-DialogLoading = "1.0.3"

gsonVersion = "2.8.8"
kotlinxCoroutinesAndroid = "1.6.4"
loggingInterceptor = "3.9.1"
markdown = "0.5.0"
okhttp = "4.11.0"
rhino = "1.7.14"
roomCompiler = "2.5.2"
round = "1.1.2"
swiperefreshlayout = "1.2.0-alpha01"
xposed = "82"
gson = "2.10.1"
htmlKtx = "1.1.2"
kotlin = "1.8.21"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
permissionx = "1.7.1"
themeEngine = "master-SNAPSHOT"
ultimateBarX = "dev-SNAPSHOT"
navigationFragment = "2.7.0"
browser = "1.6.0"
activity = "1.8.2"
constraintlayout = "2.1.4"

[libraries]
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragment" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragment" }
androidx-room-compiler-v251 = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-roomRuntime" }
androidx-room-runtime-v251 = { module = "androidx.room:room-runtime", version.ref = "androidx-roomRuntime" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
bugsnag-android = { module = "com.bugsnag:bugsnag-android", version.ref = "bugsnagAndroid" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
gson-v288 = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }
round = { module = "io.github.xiaofeidev:round", version.ref = "round" }
tobeyr1DialogLoading = { module = "com.github.Tobeyr1:DialogLoading", version.ref = "github-DialogLoading" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
html-ktx = { module = "dev.rikka.rikkax.html:html-ktx", version.ref = "htmlKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
permissionx = { module = "com.guolindev.permissionx:permissionx", version.ref = "permissionx" }

themeEngine = { module = "com.github.AnkioTomas:ThemeEngine", version.ref = "themeEngine" }

ultimateBarX = { module = "com.github.zackratos:UltimateBarX", version.ref = "ultimateBarX" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

