name: Build and Publish Android Pre-Release APKs

on:
  push:
    branches:
      - master

permissions: write-all

jobs:
  buildAndRelease: # 编译安卓

    runs-on: ubuntu-latest
    steps:
      - name: 下载代码
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 设置Java编译环境
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: 编译安卓
        run: |
          chmod +x .github/workflows/build.sh
          .github/workflows/build.sh
         

      - uses: ilharp/sign-android-release@v1
        name: 签名 # ID used to access action output
        id: sign_app
        with:
          releaseDir: release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 34.0.0


      - name: 生成构建日志
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: true
          configuration: ".github/workflows/configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传到artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-apk
          path: ${{github.workspace}}/release/*.apk

      - name: Add Changelog to Summary
        run: |
          echo "# 更新日志" >> $GITHUB_STEP_SUMMARY
          echo "- 版本：${{ env.TAG_VERSION_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- 时间：$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo ${{ steps.github_release.outputs.changelog }} >> $GITHUB_STEP_SUMMARY


      - name: 上传Apk
        id: upload_apk
        run: pip install requests markdown && python .github/workflows/upload.py
        env:
          CHANGELOG: ${{steps.github_release.outputs.changelog}}
          GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}
          HOST_ENV_VAR: ${{ secrets.HOST_ENV_VAR }}
          USERNAME_ENV_VAR: ${{ secrets.USERNAME_ENV_VAR }}
          PASSWORD_ENV_VAR: ${{ secrets.PASSWORD_ENV_VAR }}

      - name: 推送本次TAG
        run: |
          git tag "${{ env.TAG_VERSION_NAME }}"
          git push origin "${{ env.TAG_VERSION_NAME }}"
