name: Build and Publish Android Pre-Release APKs

on:
  push:
    branches:
      - master

jobs:
  buildAndRelease: # 编译安卓
    runs-on: ubuntu-latest
    steps:
      - name: Check Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build and Upload APKs
        run: |
          mkdir release
          current_time=$(date '+%Y%m%d%H%M%S')
          # 优先构建xposed版本
          for flavor in xposed ; do
            ./gradlew "assemble${flavor^}Release"
            cp app/build/outputs/apk/${flavor}/release/app.apk release/app-${flavor}-pre-$current_time.apk
          done
          ls -al .
          ls -al release

      - uses: ilharp/sign-android-release@v1
        name: Sign app APK # ID used to access action output
        id: sign_app
        with:
          releaseDir: release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Read versionName from build.gradle
        run: |
          versionName=$(grep 'versionName' app/build.gradle | sed -n 's/.*versionName "\([^"]*\)".*/\1/p' | tr -d '[:space:]')
          echo "VERSION_NAME=$versionName" >> $GITHUB_ENV
        shell: bash


      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          commitMode: true
          configuration: "configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Tag Name
        id: tag_name
        run: echo "TAG_VERSION_NAME=v${{ env.VERSION_NAME }}-night-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create And Push Tag
        run: |
          git tag "${{ env.TAG_VERSION_NAME }}"
          git push origin "${{ env.TAG_VERSION_NAME }}"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/app-*-signed.apk
          tag_name: ${{ env.TAG_VERSION_NAME }}
          body: ${{steps.github_release.outputs.changelog}}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}